apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
  namespace: argocd
spec:
  project: applicationsets
  source:
    path: projects/applicationsets
    repoURL: https://github.com/pawelkostyla/argocd-configrepo.git
    targetRevision: master
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
